export function serializeTask(task: any, includeDetails = false) {
  return {
    id: task.id,
    type: task.type,
    status: task.status,
    provider: task.provider ? {
      id: task.provider.id,
      name: task.provider.name,
      type: task.provider.type.toLowerCase().replace('_', '-'),
      baseUrl: task.provider.baseUrl,
      defaultModel: task.provider.defaultModel,
      apiMode: task.provider.apiMode.toLowerCase(),
    } : null,
    model: task.model,
    prompt: task.prompt,
    params: task.paramsJson,
    route: task.routeJson,
    diagnostics: task.diagnosticsJson,
    errorCode: task.errorCode,
    errorMessage: task.errorMessage,
    elapsedMs: task.elapsedMs,
    images: task.images.map((image: any) => ({
      id: image.id,
      storageKey: image.storageKey,
      assetUrl: `/assets/file?key=${encodeURIComponent(image.storageKey)}`,
      thumbnailUrl: image.thumbnailKey ? `/assets/file?key=${encodeURIComponent(image.thumbnailKey)}` : undefined,
      format: image.format,
      sizeBytes: image.sizeBytes,
      width: image.width,
      height: image.height,
      prompt: image.prompt,
      revisedPrompt: image.revisedPrompt,
      sourceAssetId: image.sourceAssetId,
      createdAt: image.createdAt.toISOString(),
    })),
    createdAt: task.createdAt.toISOString(),
    updatedAt: task.updatedAt.toISOString(),
    ...(includeDetails ? { raw: { paramsJson: task.paramsJson, routeJson: task.routeJson, diagnosticsJson: task.diagnosticsJson } } : {}),
  };
}
