import type { CreationObject, CreationRelation } from './types';

export const creationBoardObjects: CreationObject[] = [
  {
    id: 'brief-1',
    kind: 'brief',
    title: '创作目标 · 温润纸面护肤封面',
    summary: '用户要一张小红书首图，强调温柔、高级、产品清晰。',
    position: { x: 52, y: 72 },
    size: { width: 236, height: 116 },
    status: 'active',
    semantic: { slot: 'composition', priority: 62, keep: ['小红书首图', '温润纸面', '主体清晰'] },
    text: { role: 'prompt', content: '做一张温润纸面感护肤品小红书封面，主体清晰，留白高级。' },
  },
  {
    id: 'ref-product-1',
    kind: 'reference.image',
    title: '产品参考图',
    summary: '参考图 · 产品身份明确，优先保持瓶身和包装关键细节。',
    position: { x: 70, y: 238 },
    size: { width: 168, height: 140 },
    status: 'active',
    semantic: { slot: 'product', priority: 100, keep: ['瓶身比例', '包装标签', '瓶盖形态'] },
  },
  {
    id: 'ref-mood-1',
    kind: 'reference.image',
    title: '风格氛围参考',
    summary: '参考图 · 借温暖纸面、柔光和安静留白，不复制具体构图。',
    position: { x: 332, y: 58 },
    size: { width: 176, height: 124 },
    status: 'active',
    semantic: { slot: 'styleMood', priority: 54, borrow: ['暖纸基底', '柔和阴影', '杂志留白'] },
  },
  {
    id: 'text-title-1',
    kind: 'text',
    title: '标题文本备注',
    summary: '文本备注 · 单击打开详情，长按进入创作助手上下文。',
    position: { x: 328, y: 234 },
    size: { width: 230, height: 112 },
    selected: true,
    status: 'active',
    semantic: { slot: 'textLayout', priority: 76, keep: ['短标题', '不营销', '高级一点'] },
    text: { role: 'title', content: '把肌肤交给一束柔光', styleHint: '克制、编辑感、非促销口吻' },
  },
  {
    id: 'brand-palette-1',
    kind: 'brand.palette',
    title: '品牌色板',
    summary: '品牌色板：鼠尾草绿、暖纸白、珊瑚强调点。',
    position: { x: 594, y: 72 },
    size: { width: 190, height: 116 },
    status: 'active',
    semantic: { slot: 'brand', priority: 86, keep: ['Sage', 'Paper', 'Coral accent'] },
  },
  {
    id: 'task-gen-1',
    kind: 'task.generate',
    title: '首轮尝试',
    summary: '这次尝试只保留来源说明，不显示技术细节。',
    position: { x: 610, y: 248 },
    size: { width: 184, height: 104 },
    status: 'active',
    lineage: { sourceNodeIds: ['brief-1', 'ref-product-1', 'ref-mood-1', 'text-title-1', 'brand-palette-1'] },
  },
  {
    id: 'gen-a',
    kind: 'generated.image',
    title: '这一版 A · 柔光近景',
    summary: '这一版氛围成立，但产品边缘偏软。',
    position: { x: 880, y: 76 },
    size: { width: 190, height: 150 },
    status: 'active',
    semantic: { slot: 'resultAnchor', priority: 58, borrow: ['柔光', '近景'] },
    lineage: { sourceNodeIds: ['task-gen-1'] },
  },
  {
    id: 'gen-b',
    kind: 'generated.image',
    title: '当前最好 · 温润纸面',
    summary: '当前最好的一版，可直接说“保持这个感觉继续”。',
    position: { x: 872, y: 284 },
    size: { width: 210, height: 166 },
    status: 'champion',
    semantic: { slot: 'resultAnchor', priority: 82, borrow: ['构图', '温润氛围', '纸面质感'] },
    lineage: { sourceNodeIds: ['task-gen-1'] },
  },
  {
    id: 'gen-old',
    kind: 'generated.image',
    title: '已放弃尝试 · 过度商业',
    summary: '已放弃尝试会弱化显示，仍可回看但不抢当前最好。',
    position: { x: 1124, y: 92 },
    size: { width: 154, height: 120 },
    status: 'rejected',
    lineage: { sourceNodeIds: ['task-gen-1'] },
  },
  {
    id: 'artboard-xhs-1',
    kind: 'artboard',
    title: '小红书 3:4 交付画板',
    summary: '交付画板 · 承载主图、标题文本和品牌要求。',
    position: { x: 1138, y: 288 },
    size: { width: 176, height: 216 },
    status: 'active',
    semantic: { slot: 'composition', priority: 72, keep: ['3:4', '标题安全区', '产品居中偏下'] },
  },
  {
    id: 'deliverable-1',
    kind: 'deliverable',
    title: '交付画板 · 待导出封面',
    summary: '准备交付，后续可导出、继续改或扩展同系列。',
    position: { x: 1378, y: 330 },
    size: { width: 156, height: 120 },
    status: 'exported',
    lineage: { sourceNodeIds: ['artboard-xhs-1'] },
  },
];

export const creationBoardRelations: CreationRelation[] = [
  { id: 'edge-brief-product', sourceId: 'brief-1', targetId: 'ref-product-1', type: 'reference', strength: 'primary' },
  { id: 'edge-brief-mood', sourceId: 'brief-1', targetId: 'ref-mood-1', type: 'reference', strength: 'secondary' },
  { id: 'edge-text-artboard', sourceId: 'text-title-1', targetId: 'artboard-xhs-1', type: 'text-binding', strength: 'primary', selectedLineage: true },
  { id: 'edge-brand-artboard', sourceId: 'brand-palette-1', targetId: 'artboard-xhs-1', type: 'brand-constraint', strength: 'primary' },
  { id: 'edge-input-task', sourceId: 'ref-product-1', targetId: 'task-gen-1', type: 'generation', strength: 'primary' },
  { id: 'edge-task-gen-a', sourceId: 'task-gen-1', targetId: 'gen-a', type: 'variant', strength: 'secondary' },
  { id: 'edge-task-gen-b', sourceId: 'task-gen-1', targetId: 'gen-b', type: 'variant', strength: 'primary', selectedLineage: true },
  { id: 'edge-task-gen-old', sourceId: 'task-gen-1', targetId: 'gen-old', type: 'variant', strength: 'faded' },
  { id: 'edge-genb-artboard', sourceId: 'gen-b', targetId: 'artboard-xhs-1', type: 'adoption', strength: 'primary', selectedLineage: true },
  { id: 'edge-artboard-export', sourceId: 'artboard-xhs-1', targetId: 'deliverable-1', type: 'export', strength: 'secondary' },
];
